[teammates]
# 조원들의 IP를 여기에 적으세요.
ai-server ansible_host=10.4.1.11 # Ai  서버
web-1 ansible_host=10.4.2.10 # LB 서버 임시(나중에 10번으로 수정)
web-2 ansible_host=10.4.2.11 # web 1
web-3 ansible_host=10.4.2.12 # web 2
web-4 ansible_host=10.4.2.13 # web 3
; server_04 ansible_host=10.4.4.10 # DB 라우터 서버
db-1 ansible_host=10.4.4.11 # master db
db-2 ansible_host=10.4.4.12 # slave db 
server_05 ansible_host=10.4.5.10 # 모니터링 서버

[routers]
lb-router ansible_host=10.4.2.10

#============================Jenkins=========================================
[jenkins]
ci/cd-jenkins ansible_host=10.4.3.10

#============================AI=========================================
[ai]
server_01 ansible_host=10.4.1.11

[ai:vars]
# 중계 서버(Bastion) 설정 예시
# ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q ansible-admin@172.16.6.81"'
ansible_python_interpreter=/usr/bin/python3


#============================LB=========================================
[lb]
lb_server ansible_host=10.4.2.10

[web]
web_01 ansible_host=10.4.2.11
web_02 ansible_host=10.4.2.12
web_03 ansible_host=10.4.2.13

[lb:vars]
# ansible_ssh_private_key_file=/var/jenkins_home/.ssh/jenkins_deploy
ansible_ssh_common_args='-o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

#============================DB=========================================
[db]
DB ansible_host=10.4.4.10 # DB Router

[db_nfs]
db1 ansible_host=10.4.4.11 # DB3 (NFS)

[db_master]
db2 ansible_host=10.4.4.12  # DB1 (마스터) + NFS 서버

[db_slave]
db3 ansible_host=10.4.4.13  # DB2 (슬레이브)



[client]
AI_server ansible_host=10.4.1.11  # AI 지금 db서버랑 AI 서버 사이에 문제가 있는 듯 해당 부분 NFS 마운트 부분에서 무한로딩에 걸림 -> 0120 해결: AI 서버 마운트가 DB 라우터로 되어 있엇다
Web1 ansible_host=10.4.2.11  # web1
Web2 ansible_host=10.4.2.12  # web2
Web3 ansible_host=10.4.2.13  # web3
CICD ansible_host=10.4.3.10  # cicd
DB_master ansible_host=10.4.4.12  # DB1 (master)
DB_slave ansible_host=10.4.4.13 # DB2 (slave)
# Monitoring ansible_host=10.4.5.10  # monitoring
#============================Monitoring=========================================
[monitoring]
10.4.5.10 ansible_user=ansible-admin

[targets]
10.4.1.11  # AI
10.4.2.10  # LB
10.4.2.11  # WEB1
10.4.2.12  # WEB2
10.4.2.13  # WEB3
10.4.3.10  # Ansible
10.4.4.12  # DB1
10.4.4.13  # DB2

#============================all=========================================

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

