---
# --- 포트 설정 ---
prometheus_port: 9090
loki_port: 3100
promtail_port: 9080
blackbox_exporter_port: 9115

minio_port: 9000
minio_console_port: 9001  

# --- Loki 저장소(MinIO) 상세 설정 ---
loki_s3_endpoint: "{{ monitoring_server_ip }}:{{ minio_port }}"
loki_s3_bucket: "loki-data"

# --- 경로 및 보관 설정 ---
prometheus_db_path: "/var/lib/prometheus/"
prometheus_retention_time: "15d"
journal_max_age: "12h"

# --- MinIO 설정 ---
minio_data_path: "/mnt/NAS/minio_data"
minio_root_user: "minioadmin"
minio_root_password: "minioadmin"

# ---  Blackbox Exporter 모듈 ---
blackbox_module: "http_2xx"
